"""add_schedule_context

Revision ID: 0003_add_schedule_context
Revises: 0002_add_persona_tables
Create Date: 2026-03-29 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0003_add_schedule_context'
down_revision = '0002_add_persona_tables'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_context',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('classes_per_day', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('study_hours', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('has_deadlines', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_exam_period', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('workload_level', sa.String(length=32), server_default=sa.text("'low'"), nullable=False),
    sa.Column('stress_level', sa.Float(), server_default=sa.text('0.0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_context_user_id'), 'schedule_context', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_context_user_id'), table_name='schedule_context')
    op.drop_table('schedule_context')
    # ### end Alembic commands ###
