"""Add tracking features to messages

Revision ID: ac1bb52a64a8
Revises: 0006
Create Date: 2026-04-05 07:59:54.258576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac1bb52a64a8'
down_revision = '0006'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('emotional_intensity', sa.Float(), nullable=True))
    op.add_column('messages', sa.Column('reflection_depth', sa.Float(), nullable=True))
    op.add_column('messages', sa.Column('response_delay_ms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'response_delay_ms')
    op.drop_column('messages', 'reflection_depth')
    op.drop_column('messages', 'emotional_intensity')
    # ### end Alembic commands ###
